module.exports = {
  NUMBER: 'NUMBER',
  STRING: 'STRING',
  PAREN: 'PAREN',
  OPERATOR: 'OPERATOR',
  IDENTIFIER: 'IDENTIFIER',

  PROGRAM: 'PROGRAM',
  NUMBER_LITERAL: 'NUMBER_LITERAL',
  STRING_LITERAL: 'STRING_LITERAL',
  CALL_EXPRESSION: 'CALL_EXPRESSION',
}
