name: Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: install
    - uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: check
